#if !defined(AFX_DLGPROPSHEET_H__7FE7EC25_9C41_11D4_A181_004033572A05__INCLUDED_)
#define AFX_DLGPROPSHEET_H__7FE7EC25_9C41_11D4_A181_004033572A05__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// DlgPropSheet.h : header file
//

#include	"trafficpage.h"
#include	"detailpage.h"
#include	"historypage.h"
#include	"toolpage.h"
#include	"optionspage.h"
#include	"aboutpage.h"



/**
 * CMainSheet.
 * this class represents the propertysheet which holds all tabs.
 * most in here is generated by the class wizard of VC6.
 */
class CMainSheet : public CPropertySheet
{
	DECLARE_DYNAMIC(CMainSheet)

// Construction
public:
	CMainSheet(UINT nIDCaption, CWnd* pParentWnd = NULL, UINT iSelectPage = 0);
	CMainSheet(LPCTSTR pszCaption, CWnd* pParentWnd = NULL, UINT iSelectPage = 0);

// Attributes
public:
	CTrafficPage*		m_pTrafficPage;
	CDetailPage*		m_pDetailPage;
	CHistoryPage*		m_pHistoryPage;
	CToolPage*			m_pToolPage;
	COptionsPage*		m_pOptionsPage;
	CAboutPage*			m_pAboutPage;

  
// Operations
public:
void  AddPropPages( );

// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(DlgPropSheet)
	public:
	virtual BOOL OnInitDialog();
	virtual BOOL OnChildNotify(UINT message, WPARAM wParam, LPARAM lParam, LRESULT* pLResult);
	protected:
	virtual void PostNcDestroy();
	virtual LRESULT DefWindowProc(UINT message, WPARAM wParam, LPARAM lParam);
	//}}AFX_VIRTUAL

// Implementation
public:
	virtual ~CMainSheet();

	// Generated message map functions
protected:
	// Generated message map functions
	//{{AFX_MSG(CMainSheet)
	afx_msg void OnDestroy();
	afx_msg int OnCreate(LPCREATESTRUCT lpCreateStruct);
	afx_msg void OnPaint();
	afx_msg void OnClose();
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
private:
	void	LoadWindowPosition(CRect *rc);
	void	SaveWindowPosition(CRect *rc);
private:
	CFont	m_fontLogo;

};

/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DLGPROPSHEET_H__7FE7EC25_9C41_11D4_A181_004033572A05__INCLUDED_)
