//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by trafficwatch.rc
//
#define IDD_TRAFFICWATCH_DIALOG         102
#define IDD_MAINPAGE                    102
#define IDD_DETAILPAGE                  107
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_                  128
#define IDD_OPTIONS                     132
#define IDD_VIEW                        137
#define IDI_TASKBAR                     140
#define IDR_WORLDPIC                    145
#define IDD_ABOUT                       151
#define IDR_BMP1                        173
#define IDC_DL_BAR                      1003
#define IDC_DL_BYTESPEED                1007
#define IDC_UL_BAR                      1008
#define IDC_UL_MAXSPEED                 1009
#define IDC_UL_LANSPEED                 1009
#define IDC_DL_DATA                     1010
#define IDC_DL_MAXSPEED                 1011
#define IDC_DL_LANSPEED                 1011
#define IDC_UL_BYTESPEED                1012
#define IDC_UL_DATA                     1013
#define IDC_TOT_BYTESPEED               1014
#define IDC_TOT_MAXSPEED                1015
#define IDC_TOT_DATA                    1016
#define IDC_IP                          1017
#define IDC_MASK                        1018
#define IDC_GATEWAY                     1019
#define IDC_CONNECTIONS                 1020
#define IDC_ADAPT_DESC                  1021
#define IDC_MACADDR                     1023
#define IDC_PROGRESS_WEB_DL             1024
#define IDC_PROGRESS_WEB_UL             1025
#define IDC_PROGRESS_MAIL_DL            1026
#define IDC_PROGRESS_MAIL_UL            1027
#define IDC_PROGRESS_NEWS_DL            1028
#define IDC_PROGRESS_NEWS_UL            1029
#define IDC_PROGRESS_SHARE_DL           1030
#define IDC_PROGRESS_SHARE_UL           1031
#define IDC_PROGRESS_UDP_DL             1032
#define IDC_PROGRESS_UDP_UL             1033
#define IDC_PROGRESS_OTHER_DL           1034
#define IDC_PROGRESS_OTHER_UL           1035
#define IDC_WEB_DL_SPEED                1036
#define IDC_WEB_DL_DATA                 1037
#define IDC_WEB_UL_SPEED                1038
#define IDC_WEB_UL_DATA                 1039
#define IDC_WEB_TOTAL_DATA              1040
#define IDC_MAIL_DL_SPEED               1041
#define IDC_MAIL_DL_DATA                1042
#define IDC_MAIL_UL_SPEED               1043
#define IDC_MAIL_UL_DATA                1044
#define IDC_MAIL_TOTAL_DATA             1045
#define IDC_NEWS_DL_SPEED               1046
#define IDC_NEWS_DL_DATA                1047
#define IDC_NEWS_UL_SPEED               1048
#define IDC_NEWS_UL_DATA                1049
#define IDC_NEWS_TOTAL_DATA             1050
#define IDC_SHARE_DL_SPEED              1051
#define IDC_SHARE_DL_DATA               1052
#define IDC_SHARE_UL_SPEED              1053
#define IDC_SHARE_UL_DATA               1054
#define IDC_SHARE_TOTAL_DATA            1055
#define IDC_UDP_DL_SPEED                1056
#define IDC_UDP_DL_DATA                 1057
#define IDC_UDP_UL_SPEED                1058
#define IDC_UDP_UL_DATA                 1059
#define IDC_UDP_TOTAL_DATA              1060
#define IDC_OTHER_DL_SPEED              1061
#define IDC_OTHER_DL_DATA               1062
#define IDC_OTHER_UL_SPEED              1063
#define IDC_OTHER_UL_DATA               1064
#define IDC_OTHER_TOTAL_DATA            1065
#define IDC_AUTOSTART_CHECK             1105
#define IDC_DL_R256                     1108
#define IDC_DL_R512                     1109
#define IDC_DL_R768                     1110
#define IDC_DL_R1000                    1111
#define IDC_DL_R2000                    1112
#define IDC_DL_R5000                    1113
#define IDC_DL_R10000                   1114
#define IDC_UL_R256                     1115
#define IDC_UL_R512                     1116
#define IDC_UL_R768                     1117
#define IDC_UL_R1000                    1118
#define IDC_UL_R2000                    1119
#define IDC_UL_R5000                    1120
#define IDC_UL_R10000                   1121
#define IDC_SHOWBITS                    1122
#define IDC_SHOWIEC                     1123
#define IDC_DLAN_1M                     1124
#define IDC_DLAN_5M                     1125
#define IDC_DLAN_10M                    1126
#define IDC_DLAN_54M                    1127
#define IDC_DLAN_100M                   1128
#define IDC_DLAN_1G                     1129
#define IDC_DLAN_10G                    1130
#define IDC_ULAN_1M                     1131
#define IDC_ULAN_5M                     1132
#define IDC_EDITVIEW                    1133
#define IDC_ULAN_10M                    1133
#define IDC_ULAN_54M                    1134
#define IDC_ULAN_100M                   1135
#define IDC_COLLAPSE                    1136
#define IDC_ULAN_1G                     1136
#define IDC_ULBAR                       1137
#define IDC_DL_R10002                   1137
#define IDC_ULAN_10G                    1137
#define IDC_DLBAR                       1138
#define IDC_ULBARLAN                    1139
#define IDC_ULSTR                       1140
#define IDC_DLBARLAN                    1140
#define IDC_ADAPTER                     1141
#define IDC_UL_BARLAN                   1142
#define IDC_DL_BARLAN                   1143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1144
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
