// trafficwatch.h : main header file for the TRAFFICWATCH application
//

#if !defined(AFX_TRAFFICWATCH_H__7643C807_1B4D_47AB_987B_D8C32D5C0E45__INCLUDED_)
#define AFX_TRAFFICWATCH_H__7643C807_1B4D_47AB_987B_D8C32D5C0E45__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#ifndef __AFXWIN_H__
	#error include 'stdafx.h' before including this file for PCH
#endif

#include "resource.h"		// main symbols
#include "globals.h"
#include "winproc.h"
#include "commctrl.h"

/**
 * CTrafficwatchApp.
 * the main class of the application. generated by the MSVC wizard.
 */
class CTrafficwatchApp : public CWinApp
{
public:
	CTrafficwatchApp();
	~CTrafficwatchApp();
	CWinproc m_wnd;
	HANDLE m_mutex;


// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CTrafficwatchApp)
	public:
	virtual BOOL InitInstance();
	//}}AFX_VIRTUAL

// Implementation

	//{{AFX_MSG(CTrafficwatchApp)
		// NOTE - the ClassWizard will add and remove member functions here.
		//    DO NOT EDIT what you see in these blocks of generated code !
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

extern CTrafficwatchApp* m_pTheApp;

/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TRAFFICWATCH_H__7643C807_1B4D_47AB_987B_D8C32D5C0E45__INCLUDED_)
